---
output:
  html_document: default
  pdf_document: default
---
# Support Vector Machine

```{r}
library(tidyverse)
set.seed(1)
x <- matrix(rnorm(20 * 2), ncol = 2)
y <- c(rep(-1, 10), rep(1, 10))
x[y == 1, ] <- x[y == 1, ] + 1
dat <- tibble(x1 = x[,1], x2 = x[,2], y = as.factor(y))
```

```{r}
ggplot(dat) + geom_point(aes(x2, x1, color = y))
```


```{r}
library(e1071)
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
plot(svmfit, dat)
```

```{r}
grid <- crossing(x1 = modelr::seq_range(dat$x1, 50), x2 = modelr::seq_range(dat$x2, 50))  %>% 
    modelr::add_predictions(svmfit)
ggplot(dat) + geom_point(aes(x2, x1, color = y)) + geom_contour(data = grid, aes(x2, x1, z = as.numeric(pred)), binwidth = 1)
```

```{r}
svmfit$index  # support vectors
```

```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "linear", cost = 1, scale = FALSE)
e1071::plot(svmfit, dat)
svmfit$index
```

```{r}
set.seed(1)
tune_out <- tune(svm, y ~ ., data = dat, kernel = "linear",
                 ranges = list(cost = c(0.001, 0.01, 0.1, 1, 5, 10, 100)))
summary(tune_out)
```

```{r}
bestmod <- tune_out$best.model
summary(bestmod)
```


```{r}
xtest <- matrix(rnorm(20 * 2), ncol = 2)
ytest <- sample(c(-1, 1), 20, rep = TRUE)
xtest[ytest == 1, ] <- xtest[ytest == 1, ] + 1
testdat <- tibble(x1 = xtest[, 1], x2 = xtest[, 2], y = as.factor(ytest))
```

```{r}
testdat %>% modelr::add_predictions(bestmod) %>% count(y, pred) %>% spread(pred, "n")
```

# Other kernels

```{r}
set.seed(1)
x <- matrix(rnorm(200 * 2), ncol = 2)
x[1:100, ] <- x[1:100, ] + 2
x[101:150, ] <- x[101:150, ] - 2
y <- c(rep(1, 150), rep(2, 50))
dat <- tibble(x1 = x[,1], x2 = x[,2], y = as.factor(y))
```

```{r}
ggplot(dat) + geom_point(aes(x2, x1, color = y))
```


```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "radial", gamma = 1, cost = 1)
plot(svmfit, dat)
```

```{r}
summary(svmfit)
svmfit <- svm(y ~ ., data = dat, kernel = "radial", gamma = 1, cost = 1e5)
plot(svmfit, dat)
```

```{r}
set.seed(1)
tune_out <- tune(svm, y ~ ., data = dat, kernel = "radial",
                 ranges = list(cost = c(0.1, 1, 10, 100, 1000), gamma = c(0.1, 0.5, 1, 2, 3, 4)))
# summary(tune_out)
plot(tune_out$best.model, dat)
```


###SVM with multiple classes

```{r}
set.seed(1)
x <- rbind(x, matrix(rnorm(50 * 2), ncol = 2))
y <- c(y, rep(0, 50))
x[y == 0, 2] <- x[y == 0, 2] + 2
dat <- tibble(x1 = x[,1], x2 = x[,2], y = as.factor(y))
```

```{r}
ggplot(dat) + geom_point(aes(x2, x1, color = y))
```


```{r}
svmfit <- svm(y ~ ., data = dat, kernel = "radial", cost = 10, gamma = 1)
plot(svmfit, dat)
```
